spring.application.name=MarketApp
server.port=8080
management.server.port=8101

spring.r2dbc.username=postgres
spring.r2dbc.password=postgres
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/postgres

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
spring.liquibase.contexts=dev
spring.liquibase.url=jdbc:postgresql://localhost:5432/postgres
spring.liquibase.user=postgres
spring.liquibase.password=postgres

spring.sql.init.mode=never

spring.data.redis.host=localhost
spring.data.redis.port=6379

cache.items.ttl-minutes=2

payment-service.base-url=http://localhost:8081

management.endpoints.web.exposure.include=health,info
