spring.application.name=auth-service
server.port=9000

spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration,\
  org.springframework.boot.autoconfigure.data.r2dbc.R2dbcDataAutoConfiguration,\
  org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration

auth-service.issuer-uri=${AUTH_SERVICE_ISSUER_URI:http://localhost:9000}
auth-service.client-id=${AUTH_SERVICE_CLIENT_ID:market-service}
auth-service.client-secret=${AUTH_SERVICE_CLIENT_SECRET:market-service-secret}

management.endpoints.web.exposure.include=health,info
