FROM eclipse-temurin:21-jdk AS builder

WORKDIR /app

COPY gradlew gradlew.bat settings.gradle build.gradle ./
COPY gradle gradle
COPY payment-api payment-api
COPY payment-service payment-service
COPY market-service market-service

RUN sed -i 's/\r$//' gradlew && chmod +x gradlew && ./gradlew :payment-service:bootJar -x test --no-daemon

FROM eclipse-temurin:21-jre

WORKDIR /app

COPY --from=builder /app/payment-service/build/libs/payment-service.jar app.jar

EXPOSE 8081

ENTRYPOINT ["java", "-jar", "app.jar"]
