FROM eclipse-temurin:21-jdk AS builder

WORKDIR /app

COPY gradlew gradlew.bat settings.gradle build.gradle ./
COPY gradle gradle
COPY payment-api payment-api
COPY market-service market-service
COPY payment-service payment-service

RUN sed -i 's/\r$//' gradlew && chmod +x gradlew && ./gradlew :market-service:bootJar -x test --no-daemon

FROM eclipse-temurin:21-jre

WORKDIR /app

COPY --from=builder /app/market-service/build/libs/market-service.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
