openapi: 3.0.0
info:
  title: ContrasTech API
  version: 1.0.0
paths:
  /api/v1/contras-tech/params:
    get:
      tags:
        - ContrasTech
      operationId: getContrasTechParams
      summary: Получить список всех параметров
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContrasTechCameraParams'
components:
  schemas:
    ContrasTechCameraParams:
      type: object
      properties:
        exposure:
          type: number
        exposureMin:
          type: number
        exposureMax:
          type: number
        fps:
          type: number
        fpsMin:
          type: number
        fpsMax:
          type: number
        fpsEnabled:
          type: number
        gain:
          type: number
        redGain:
          type: number
        greenGain:
          type: number
        blueGain:
          type: number
      required:
        - id
        - name